PREFIX=/usr/local

install:
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	cp -f via $(DESTDIR)$(PREFIX)/bin/via
	cp -f via-open $(DESTDIR)$(PREFIX)/bin/via-open

uninstall:
	rm -f $(DESTDIR)$(PREFIX)/bin/via
	rm -f $(DESTDIR)$(PREFIX)/bin/via-open
